language: go
install:
  - go get -a github.com/soundcloud/doozer
  - go get -a github.com/soundcloud/cotterpin
  - pushd /home/travis/gopath/src/github.com/soundcloud
  - git clone git://github.com/soundcloud/doozerd.git
  - pushd doozerd
  - make compile
  - /home/travis/gopath/bin/doozerd -hist=100 -w=false &> /dev/null &
  - sleep 3
  - nc -z 127.0.0.1 8046
  - popd
  - popd
script:
  - pushd /home/travis/gopath/src/github.com/soundcloud/visor
  - go test -v
