language: go
install:
  - go get -a code.google.com/p/goprotobuf/proto
  - go get -a code.google.com/p/go.net/websocket
  - go get -a github.com/soundcloud/doozer
  - go get -a github.com/soundcloud/cotterpin
  - mkdir -p $GOPATH/src/github.com/soundcloud/visor
  - mv * $GOPATH/src/github.com/soundcloud/visor
  - mkdir -p $GOPATH/src/github.com/soundcloud
  - pushd $GOPATH/src/github.com/soundcloud
  - git clone git://github.com/soundcloud/doozerd.git
  - pushd doozerd
  - make compile
  - ./doozerd -hist=100 &
  - sleep 3
  - nc -z 127.0.0.1 8046
  - popd
  - popd
script:
  - pushd $GOPATH/src/github.com/soundcloud/visor
  - go test -v
