language: go
install:
  - mkdir -p $GOPATH/src/github.com/soundcloud/visor
  - mv * $GOPATH/src/github.com/soundcloud/visor
  - pushd /tmp
  - git clone git://github.com/soundcloud/doozerd.git
  - pushd doozerd
  - make compile
  - ./doozerd -hist=100 &> /dev/null
  - sleep 3
  - nc -z 127.0.0.1 8046
  - popd
  - popd
  - go get github.com/soundcloud/doozer
  - go get github.com/soundcloud/cotterpin
script:
  - pushd $GOPATH/src/github.com/soundcloud/visor
  - go test -v
