language: go
install:
  - go get -a -v github.com/soundcloud/doozer
  - go get -a -v github.com/soundcloud/doozerd
  - go get -a -v github.com/soundcloud/cotterpin
  - mkdir -p $GOPATH/src/github.com/soundcloud/visor
  - mv * $GOPATH/src/github.com/soundcloud/visor
  - pushd $GOPATH/src/github.com/soundcloud/doozerd
  - make compile
  - ./doozerd -hist=100 &> /dev/null
  - sleep 3
  - nc -z 127.0.0.1 8046
  - popd
script:
  - pushd $GOPATH/src/github.com/soundcloud/visor
  - go test -v
