language: go
go: 1.4.2

install:
  - go get -a github.com/soundcloud/doozer
  - go get -a github.com/soundcloud/doozerd
  - go get -a github.com/soundcloud/cotterpin
  - /home/travis/gopath/bin/doozerd -solo -w=false &> /dev/null &
  - sleep 3
  - nc -z 127.0.0.1 8046
script:
  - pushd /home/travis/gopath/src/github.com/soundcloud/visor
  - go test -v ./...
